#!/usr/bin/env node
const { program } = require('commander');
// const package = require('../package.json');

program
  .description('Compares two configuration files and shows a difference.')

program
  .option('-V, --version', 'output the version number')
  program.parse();

function diff(file1, file2) {

}

module.exports = { diff };